// <copyright file="NntpSpoolStartupConfigLogHostedService.Logging.cs" company="Usenet Ninja">
// Copyright (c) Chris Knipe &lt;cknipe@opticnetworks.net&gt;. Licensed under the Apache License, Version 2.0 (see LICENSE).
// </copyright>
// EventId 1 (transit spool startup configuration snapshot).

namespace Vector.NNTP.Articles.DependencyInjection
{
    /// <summary>
    /// Source-generated <see cref="LoggerMessageAttribute"/> helper for the transit spool startup configuration log.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="SpoolConfigured"/> is invoked once per host start from the private startup hosted service registered by
    /// <see cref="ServiceCollectionExtensions.AddNntpArticlesTransitSpool"/>. It confirms effective paths and queue
    /// limits after <see cref="Diagnostics.SpoolDirectoryUtilities"/> normalization — not raw configuration strings.
    /// </para>
    /// <para>
    /// Steady-state spool failures and writer scaling are logged elsewhere (<see cref="Storage.NntpSpoolWriterPump"/>,
    /// <see cref="Storage.NntpSpoolWriterPool"/>). This type emits only the startup snapshot.
    /// </para>
    /// </remarks>
    internal static partial class NntpSpoolStartupConfigLog
    {
        /// <summary>
        /// Emits a single information log with resolved transit spool paths and queue admission limits.
        /// </summary>
        /// <param name="logger">
        /// Category logger from the startup hosted service (typically
        /// <c>ILogger&lt;NntpSpoolStartupConfigLogHostedService&gt;</c>).
        /// </param>
        /// <param name="spoolRoot">
        /// Canonical absolute spool root from <see cref="Diagnostics.SpoolDirectoryUtilities.ResolveSpoolDirectory"/>.
        /// </param>
        /// <param name="incoming">
        /// Incoming article directory from <see cref="Diagnostics.SpoolDirectoryUtilities.GetIncomingDirectory"/>,
        /// typically <c>{spoolRoot}/Incoming</c>.
        /// </param>
        /// <param name="queueCapacity">
        /// Bounded queue item cap from <see cref="Sockets.Configuration.NntpServerOptions.SpoolQueueCapacity"/>.
        /// </param>
        /// <param name="maxQueuedBytes">
        /// Bounded queued-byte budget from <see cref="Sockets.Configuration.NntpServerOptions.MaxQueuedBytes"/>.
        /// </param>
        /// <param name="pathAppend">
        /// Configured <c>Path</c> header append token from <see cref="Sockets.Configuration.NntpServerOptions.PathAppend"/>.
        /// May be empty when path mutation is disabled.
        /// </param>
        /// <remarks>
        /// <para>
        /// <b>Event:</b> EventId <c>1</c>, <see cref="LogLevel.Information"/>. Message template:
        /// <c>NNTP transit spool configured: Root={SpoolRoot}, Incoming={Incoming}, QueueCapacity={QueueCapacity}, MaxQueuedBytes={MaxQueuedBytes}, PathAppend='{PathAppend}'.</c>
        /// </para>
        /// <para>
        /// <b>Timing:</b> Called synchronously from the hosted service <c>StartAsync</c> hook before writer workers begin
        /// dequeuing. Options changes after startup are not re-logged by this event.
        /// </para>
        /// <para>
        /// <b>Implementation:</b> Body is source-generated by <see cref="LoggerMessageAttribute"/>; callers should not
        /// add a manual implementation.
        /// </para>
        /// </remarks>
        [LoggerMessage(
            EventId = 1,
            Level = LogLevel.Information,
            Message = "NNTP transit spool configured: Root={SpoolRoot}, Incoming={Incoming}, QueueCapacity={QueueCapacity}, MaxQueuedBytes={MaxQueuedBytes}, PathAppend='{PathAppend}'.")]
        public static partial void SpoolConfigured(
            ILogger logger,
            string spoolRoot,
            string incoming,
            int queueCapacity,
            long maxQueuedBytes,
            string pathAppend);
    }
}
